### ISSUE TITLE
std::unary_functionは変更が必要

### ISSUE THREAD

**Issue by tntakahashi** [spadi-alliance/hul-common-lib#22]
```c++
    class BitDump
      : public std::unary_function<unsigned int, void>
    {
    private:
```
std::unary_functionはC++11でdeprecated, C++17でremovedになりました。
最近のmacOSでコンパイルできないようです。

**Comment by RyotaroHonda** [comment]
std::unary_function<unsigned int, void>の継承を削除しました。コンパイルは出来ているが未テスト。
ついでにUncopyable.hhを削除。
#23
